[package]
name = "blockchain"
version = "0.1.0"
edition = "2021"

[dependencies]
crypto-hash = "0.3.4"
serde = {version = "1.0.196", features=["derive"]}
serde_json = "1.0.114"
time = {version = "0.3.33", features = ["macros","serde", "formatting","parsing"]}
time-macros = "0.2.17"

